export const dictionary = {
  en: {
    headerQuote: "Education is the natural right of all children.",
    committee: "Our Committee",
    career: "Career",
    headoffice: "Head Office",
    feedback: "Feedback",
    tos: "Terms and Condition",
    company: "Company",
    usefulLinks: "Useful Links",
    services: "Services",
    phone: "9851353599",
    address: "Lalitpur, Nepal",
  },
  np: {
    headerQuote: "शिक्षा प्राप्त गर्नु सबै बालबालिकाको नैसर्गिक अधिकार हो ।",
    committee: "संचालक समिति ",
    career: "क्यारियर",
    headoffice: "ललितपुर, नेपाल",
    feedback: "प्रतिक्रिया",
    tos: "नियम र शर्त",
    company: "कम्पनी",
    address: "ललितपुर, नेपाल",
    services: "हाम्रा सेवाहरु",
    phone: "९८५१३५३५९९",
    homeWelcomContent: "",
    contactContent: "",
  },
};
